export type Country = {
  name: string;
  flag: string;
  slug: string;
};

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", flag: "🇦🇫", slug: "afghanistan" },
  { name: "Albania", flag: "🇦🇱", slug: "albania" },
  { name: "Algeria", flag: "🇩🇿", slug: "algeria" },
  { name: "Andorra", flag: "🇦🇩", slug: "andorra" },
  { name: "Angola", flag: "🇦🇴", slug: "angola" },
  { name: "Antigua and Barbuda", flag: "🇦🇬", slug: "antigua-and-barbuda" },
  { name: "Argentina", flag: "🇦🇷", slug: "argentina" },
  { name: "Armenia", flag: "🇦🇲", slug: "armenia" },
  { name: "Australia", flag: "🇦🇺", slug: "australia" },
  { name: "Austria", flag: "🇦🇹", slug: "austria" },
  { name: "Azerbaijan", flag: "🇦🇿", slug: "azerbaijan" },
  { name: "Bahamas", flag: "🇧🇸", slug: "bahamas" },
  { name: "Bahrain", flag: "🇧🇭", slug: "bahrain" },
  { name: "Bangladesh", flag: "🇧🇩", slug: "bangladesh" },
  { name: "Barbados", flag: "🇧🇧", slug: "barbados" },
  { name: "Belarus", flag: "🇧🇾", slug: "belarus" },
  { name: "Belgium", flag: "🇧🇪", slug: "belgium" },
  { name: "Belize", flag: "🇧🇿", slug: "belize" },
  { name: "Benin", flag: "🇧🇯", slug: "benin" },
  { name: "Bhutan", flag: "🇧🇹", slug: "bhutan" },
  { name: "Bolivia", flag: "🇧🇴", slug: "bolivia" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", slug: "bosnia-and-herzegovina" },
  { name: "Botswana", flag: "🇧🇼", slug: "botswana" },
  { name: "Brazil", flag: "🇧🇷", slug: "brazil" },
  { name: "Brunei", flag: "🇧🇳", slug: "brunei" },
  { name: "Bulgaria", flag: "🇧🇬", slug: "bulgaria" },
  { name: "Burkina Faso", flag: "🇧🇫", slug: "burkina-faso" },
  { name: "Burundi", flag: "🇧🇮", slug: "burundi" },
  { name: "Cabo Verde", flag: "🇨🇻", slug: "cabo-verde" },
  { name: "Cambodia", flag: "🇰🇭", slug: "cambodia" },
  { name: "Cameroon", flag: "🇨🇲", slug: "cameroon" },
  { name: "Canada", flag: "🇨🇦", slug: "canada" },
  {
    name: "Central African Republic",
    flag: "🇨🇫",
    slug: "central-african-republic",
  },
  { name: "Chad", flag: "🇹🇩", slug: "chad" },
  { name: "Chile", flag: "🇨🇱", slug: "chile" },
  { name: "China", flag: "🇨🇳", slug: "china" },
  { name: "Colombia", flag: "🇨🇴", slug: "colombia" },
  { name: "Comoros", flag: "🇰🇲", slug: "comoros" },
  { name: "Congo (Republic of the)", flag: "🇨🇬", slug: "congo-republic-of-the" },
  { name: "Costa Rica", flag: "🇨🇷", slug: "costa-rica" },
  { name: "Croatia", flag: "🇭🇷", slug: "croatia" },
  { name: "Cuba", flag: "🇨🇺", slug: "cuba" },
  { name: "Cyprus", flag: "🇨🇾", slug: "cyprus" },
  { name: "Czechia", flag: "🇨🇿", slug: "czechia" },
  {
    name: "Democratic Republic of the Congo",
    flag: "🇨🇩",
    slug: "democratic-republic-of-the-congo",
  },
  { name: "Denmark", flag: "🇩🇰", slug: "denmark" },
  { name: "Djibouti", flag: "🇩🇯", slug: "djibouti" },
  { name: "Dominica", flag: "🇩🇲", slug: "dominica" },
  { name: "Dominican Republic", flag: "🇩🇴", slug: "dominican-republic" },
  { name: "Ecuador", flag: "🇪🇨", slug: "ecuador" },
  { name: "Egypt", flag: "🇪🇬", slug: "egypt" },
  { name: "El Salvador", flag: "🇸🇻", slug: "el-salvador" },
  { name: "Equatorial Guinea", flag: "🇬🇶", slug: "equatorial-guinea" },
  { name: "Eritrea", flag: "🇪🇷", slug: "eritrea" },
  { name: "Estonia", flag: "🇪🇪", slug: "estonia" },
  { name: "Eswatini", flag: "🇸🇿", slug: "eswatini" },
  { name: "Ethiopia", flag: "🇪🇹", slug: "ethiopia" },
  { name: "Fiji", flag: "🇫🇯", slug: "fiji" },
  { name: "Finland", flag: "🇫🇮", slug: "finland" },
  { name: "France", flag: "🇫🇷", slug: "france" },
  { name: "Gabon", flag: "🇬🇦", slug: "gabon" },
  { name: "Gambia", flag: "🇬🇲", slug: "gambia" },
  { name: "Georgia", flag: "🇬🇪", slug: "georgia" },
  { name: "Germany", flag: "🇩🇪", slug: "germany" },
  { name: "Ghana", flag: "🇬🇭", slug: "ghana" },
  { name: "Greece", flag: "🇬🇷", slug: "greece" },
  { name: "Grenada", flag: "🇬🇩", slug: "grenada" },
  { name: "Guatemala", flag: "🇬🇹", slug: "guatemala" },
  { name: "Guinea", flag: "🇬🇳", slug: "guinea" },
  { name: "Guinea-Bissau", flag: "🇬🇼", slug: "guinea-bissau" },
  { name: "Guyana", flag: "🇬🇾", slug: "guyana" },
  { name: "Haiti", flag: "🇭🇹", slug: "haiti" },
  { name: "Honduras", flag: "🇭🇳", slug: "honduras" },
  { name: "Hungary", flag: "🇭🇺", slug: "hungary" },
  { name: "Iceland", flag: "🇮🇸", slug: "iceland" },
  { name: "India", flag: "🇮🇳", slug: "india" },
  { name: "Indonesia", flag: "🇮🇩", slug: "indonesia" },
  { name: "Iran", flag: "🇮🇷", slug: "iran" },
  { name: "Iraq", flag: "🇮🇶", slug: "iraq" },
  { name: "Ireland", flag: "🇮🇪", slug: "ireland" },
  { name: "Israel", flag: "🇮🇱", slug: "israel" },
  { name: "Italy", flag: "🇮🇹", slug: "italy" },
  { name: "Jamaica", flag: "🇯🇲", slug: "jamaica" },
  { name: "Japan", flag: "🇯🇵", slug: "japan" },
  { name: "Jordan", flag: "🇯🇴", slug: "jordan" },
  { name: "Kazakhstan", flag: "🇰🇿", slug: "kazakhstan" },
  { name: "Kenya", flag: "🇰🇪", slug: "kenya" },
  { name: "Kiribati", flag: "🇰🇮", slug: "kiribati" },
  { name: "Kuwait", flag: "🇰🇼", slug: "kuwait" },
  { name: "Kyrgyzstan", flag: "🇰🇬", slug: "kyrgyzstan" },
  { name: "Laos", flag: "🇱🇦", slug: "laos" },
  { name: "Latvia", flag: "🇱🇻", slug: "latvia" },
  { name: "Lebanon", flag: "🇱🇧", slug: "lebanon" },
  { name: "Lesotho", flag: "🇱🇸", slug: "lesotho" },
  { name: "Liberia", flag: "🇱🇷", slug: "liberia" },
  { name: "Libya", flag: "🇱🇾", slug: "libya" },
  { name: "Liechtenstein", flag: "🇱🇮", slug: "liechtenstein" },
  { name: "Lithuania", flag: "🇱🇹", slug: "lithuania" },
  { name: "Luxembourg", flag: "🇱🇺", slug: "luxembourg" },
  { name: "Madagascar", flag: "🇲🇬", slug: "madagascar" },
  { name: "Malawi", flag: "🇲🇼", slug: "malawi" },
  { name: "Malaysia", flag: "🇲🇾", slug: "malaysia" },
  { name: "Maldives", flag: "🇲🇻", slug: "maldives" },
  { name: "Mali", flag: "🇲🇱", slug: "mali" },
  { name: "Malta", flag: "🇲🇹", slug: "malta" },
  { name: "Marshall Islands", flag: "🇲🇭", slug: "marshall-islands" },
  { name: "Mauritania", flag: "🇲🇷", slug: "mauritania" },
  { name: "Mauritius", flag: "🇲🇺", slug: "mauritius" },
  { name: "Mexico", flag: "🇲🇽", slug: "mexico" },
  { name: "Micronesia", flag: "🇫🇲", slug: "micronesia" },
  { name: "Moldova", flag: "🇲🇩", slug: "moldova" },
  { name: "Monaco", flag: "🇲🇨", slug: "monaco" },
  { name: "Mongolia", flag: "🇲🇳", slug: "mongolia" },
  { name: "Montenegro", flag: "🇲🇪", slug: "montenegro" },
  { name: "Morocco", flag: "🇲🇦", slug: "morocco" },
  { name: "Mozambique", flag: "🇲🇿", slug: "mozambique" },
  { name: "Myanmar", flag: "🇲🇲", slug: "myanmar" },
  { name: "Namibia", flag: "🇳🇦", slug: "namibia" },
  { name: "Nauru", flag: "🇳🇷", slug: "nauru" },
  { name: "Nepal", flag: "🇳🇵", slug: "nepal" },
  { name: "Netherlands", flag: "🇳🇱", slug: "netherlands" },
  { name: "New Zealand", flag: "🇳🇿", slug: "new-zealand" },
  { name: "Nicaragua", flag: "🇳🇮", slug: "nicaragua" },
  { name: "Niger", flag: "🇳🇪", slug: "niger" },
  { name: "Nigeria", flag: "🇳🇬", slug: "nigeria" },
  { name: "North Korea", flag: "🇰🇵", slug: "north-korea" },
  { name: "North Macedonia", flag: "🇲🇰", slug: "north-macedonia" },
  { name: "Norway", flag: "🇳🇴", slug: "norway" },
  { name: "Oman", flag: "🇴🇲", slug: "oman" },
  { name: "Pakistan", flag: "🇵🇰", slug: "pakistan" },
  { name: "Palau", flag: "🇵🇼", slug: "palau" },
  { name: "Palestine", flag: "🇵🇸", slug: "palestine" },
  { name: "Panama", flag: "🇵🇦", slug: "panama" },
  { name: "Papua New Guinea", flag: "🇵🇬", slug: "papua-new-guinea" },
  { name: "Paraguay", flag: "🇵🇾", slug: "paraguay" },
  { name: "Peru", flag: "🇵🇪", slug: "peru" },
  { name: "Philippines", flag: "🇵🇭", slug: "philippines" },
  { name: "Poland", flag: "🇵🇱", slug: "poland" },
  { name: "Portugal", flag: "🇵🇹", slug: "portugal" },
  { name: "Qatar", flag: "🇶🇦", slug: "qatar" },
  { name: "Romania", flag: "🇷🇴", slug: "romania" },
  { name: "Russia", flag: "🇷🇺", slug: "russia" },
  { name: "Rwanda", flag: "🇷🇼", slug: "rwanda" },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳", slug: "saint-kitts-and-nevis" },
  { name: "Saint Lucia", flag: "🇱🇨", slug: "saint-lucia" },
  {
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    slug: "saint-vincent-and-the-grenadines",
  },
  { name: "Samoa", flag: "🇼🇸", slug: "samoa" },
  { name: "San Marino", flag: "🇸🇲", slug: "san-marino" },
  { name: "Sao Tome and Principe", flag: "🇸🇹", slug: "sao-tome-and-principe" },
  { name: "Saudi Arabia", flag: "🇸🇦", slug: "saudi-arabia" },
  { name: "Senegal", flag: "🇸🇳", slug: "senegal" },
  { name: "Serbia", flag: "🇷🇸", slug: "serbia" },
  { name: "Seychelles", flag: "🇸🇨", slug: "seychelles" },
  { name: "Sierra Leone", flag: "🇸🇱", slug: "sierra-leone" },
  { name: "Singapore", flag: "🇸🇬", slug: "singapore" },
  { name: "Slovakia", flag: "🇸🇰", slug: "slovakia" },
  { name: "Slovenia", flag: "🇸🇮", slug: "slovenia" },
  { name: "Solomon Islands", flag: "🇸🇧", slug: "solomon-islands" },
  { name: "Somalia", flag: "🇸🇴", slug: "somalia" },
  { name: "South Africa", flag: "🇿🇦", slug: "south-africa" },
  { name: "South Korea", flag: "🇰🇷", slug: "south-korea" },
  { name: "South Sudan", flag: "🇸🇸", slug: "south-sudan" },
  { name: "Spain", flag: "🇪🇸", slug: "spain" },
  { name: "Sri Lanka", flag: "🇱🇰", slug: "sri-lanka" },
  { name: "Sudan", flag: "🇸🇩", slug: "sudan" },
  { name: "Suriname", flag: "🇸🇷", slug: "suriname" },
  { name: "Sweden", flag: "🇸🇪", slug: "sweden" },
  { name: "Switzerland", flag: "🇨🇭", slug: "switzerland" },
  { name: "Syria", flag: "🇸🇾", slug: "syria" },
  { name: "Tajikistan", flag: "🇹🇯", slug: "tajikistan" },
  { name: "Tanzania", flag: "🇹🇿", slug: "tanzania" },
  { name: "Thailand", flag: "🇹🇭", slug: "thailand" },
  { name: "Timor-Leste", flag: "🇹🇱", slug: "timor-leste" },
  { name: "Togo", flag: "🇹🇬", slug: "togo" },
  { name: "Tonga", flag: "🇹🇴", slug: "tonga" },
  { name: "Trinidad and Tobago", flag: "🇹🇹", slug: "trinidad-and-tobago" },
  { name: "Tunisia", flag: "🇹🇳", slug: "tunisia" },
  { name: "Turkey", flag: "🇹🇷", slug: "turkey" },
  { name: "Turkmenistan", flag: "🇹🇲", slug: "turkmenistan" },
  { name: "Tuvalu", flag: "🇹🇻", slug: "tuvalu" },
  { name: "Uganda", flag: "🇺🇬", slug: "uganda" },
  { name: "Ukraine", flag: "🇺🇦", slug: "ukraine" },
  { name: "United Arab Emirates", flag: "🇦🇪", slug: "united-arab-emirates" },
  { name: "United Kingdom", flag: "🇬🇧", slug: "united-kingdom" },
  { name: "United States", flag: "🇺🇸", slug: "united-states" },
  { name: "Uruguay", flag: "🇺🇾", slug: "uruguay" },
  { name: "Uzbekistan", flag: "🇺🇿", slug: "uzbekistan" },
  { name: "Vanuatu", flag: "🇻🇺", slug: "vanuatu" },
  { name: "Vatican City", flag: "🇻🇦", slug: "vatican-city" },
  { name: "Venezuela", flag: "🇻🇪", slug: "venezuela" },
  { name: "Vietnam", flag: "🇻🇳", slug: "vietnam" },
  { name: "Yemen", flag: "🇾🇪", slug: "yemen" },
  { name: "Zambia", flag: "🇿🇲", slug: "zambia" },
  { name: "Zimbabwe", flag: "🇿🇼", slug: "zimbabwe" },
];
